### PR TITLE
Add CRX3 support

### PR DESCRIPTION
**Pull request by NeoRaider**
Google servers recently started sending empty replies when
acceptformat=crx2,crx3 is not passed. Add the option to the URL query
and switch to unzip-crx-3, which supports both CRX v2 and v3.

Closes: #139

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
Can you add one such extension to the test suite to validate this change?

**Comment by NeoRaider** [comment]
The current version of the React Developer Tools is affected, so this is already covered by the tests.

**Comment by ssotangkur** [comment]
Can this be merged in? I don't think the failing test has anything to do with these changes.

**Comment by ssotangkur** [comment]
> The current version of the React Developer Tools is affected, so this is already covered by the tests.

@MarshallOfSound  does this satisfy your desire to have an extension in the CRX3 format as part of the tests?

**Pull request merged**
