### PR TITLE
Updated cross-unzip and win-7zip

### PR DESCRIPTION
**Pull request by quantummkv**
Updated cross-unzip and win-7zip to fix devtools installations and webpack errors on windows.

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
> fix devtools installations and webpack errors on windows.

I've used this module on windows extensively, can you explain in more detail what issues this fixes and how it fixes them so I can better judge if these package changes could negatively impact any users

**Comment by quantummkv** [comment]
On electron 1.7.3 on Windows 10, Webpack was giving this error

```
ERROR in ./~/7zip/index.js
    Module not found: Error: Can't resolve './package' in 'E:\electron\nighthawk\node_modules\7zip'
     @ ./~/7zip/index.js 2:10-30
     @ ./~/cross-unzip/index.js
     @ ./~/electron-devtools-installer/dist/downloadChromeExtension.js
     @ ./~/electron-devtools-installer/dist/index.js
     @ ./src/main.ts
     @ multi ./src/main.ts
```

After updating these two dependencies, the error is gone. Apparently the module maintainer changed the package name after fixing this error.

**Comment by Tenga** [comment]
I've also encountered this issue on OSX. While extensions still install and run fine (I assume `cross-unzip` doesn't use `7zip`/`win-7zip` on OSX), it still spits out the exact same errors.

**Comment by MarshallOfSound** [comment]
Sorry I haven't gotten to this recently, will try to test this out on my windows machine ASAP

**Comment by MarshallOfSound** [comment]
See #60

**Pull request closed without merging**
