### PR TITLE
fix(extension): unrecognized manifest key

### PR DESCRIPTION
**Pull request by BlackHole1**

### CODE REVIEW

**Review by BrunoS3D — APPROVED** [review]
LGTM :rocket:

**Comment by BlackHole1** [comment]
@MarshallOfSound When can this PR be merged?

**Comment by BlackHole1** [comment]
@MarshallOfSound Is there something wrong with this PR that needs to be changed? If yes, please let me know and I will fix it.

**Review by prince-chrismc — APPROVED** [review]

**Comment by dewinterjack** [comment]
It would be good to get this merged

**Comment by BlackHole1** [comment]
> It would be good to get this merged

In fact, this is actually a bug in chromium and electron, and this PR is only useful to block them downstream. The best thing to do is to submit separate PRs for chromium and electron, in fact I'm already doing it, here are the PRs I submitted to them you can follow the latest progress through these.

https://chromium-review.googlesource.com/c/chromium/src/+/2959994

https://github.com/electron/electron/pull/29695

**Review by jeffdanielperso — APPROVED** [review]

**Comment by agentschmitt** [comment]
would be really nice to have the annoying warnings gone :)

**Comment by BlackHole1** [comment]
I will close this PR as the fix PR I submitted to electron has been merged.

Not sure which version electron will put this fix PR on yet, but I'll be in communication with them. It's not expected to be too far away.

**Comment by BlackHole1** [comment]
PR will be present in 16.x.

**Comment by BlackHole1** [comment]
I have written another similar library to solve this problem

This library has the same capabilities as this one, which incidentally solves the https://github.com/MarshallOfSound/electron-devtools-installer/issues/205 problem

repo: https://github.com/BlackHole1/electron-devtools-vendor
npm: electron-devtools-vendor

**Comment by MarshallOfSound** [comment]
Advertising other modules to capitalize off of SEO of an existing module is bad form.  Please do not do so, I'd normally let it slide but doing it across multiple issues shows clear intent.

**Pull request closed without merging**
